### ISSUE TITLE
dynamic pass username 

### ISSUE THREAD

**Issue by hissro** [Jaideep25/Videolify#4]
Hello 
how  i do  dynamic pass username to room and just open the call windows. 

regards

**Comment by Jaideep25** [comment]
Hey hissro,
Could you please explain the topic in detail?
Thanks ;)

**Comment by miroslavpejic85** [comment]
I think he wanted this:

https://videolify.up.railway.app/join?room=test&name=mirotalk&audio=0&video=0&screen=0&notify=0

| Params | Type    | Description     |
| ------ | ------- | --------------- |
| room   | string  | room Id         |
| name   | string  | user name       |
| audio  | boolean | audio stream    |
| video  | boolean | video stream    |
| screen | boolean | screen stream   |
| notify | boolean | welcome message |

You can join directly to the room by the params ;)

Regards.

**Comment by Jaideep25** [comment]
Oh, right.
Thanks @miroslavpejic85  ! ;)

**Comment by Jaideep25** [comment]
Hey @hissro ,
Please abide by the [LICENSE](https://github.com/Jaideep25/Videolify/blob/master/LICENSE) 
![image](https://user-images.githubusercontent.com/67269475/214770662-dc84e9be-2237-44c5-ac74-286e8163312a.png)

Thanks ;)

**Comment by hissro** [comment]
hello there  
thanks alot. I am very grateful. 

regards
